# Generated by Django 5.1.5 on 2025-01-15 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses/preview/%Y/%m/%d', verbose_name='Course Preview')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lesson Description')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/preview/%Y/%m/%d', verbose_name='Lesson Preview')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['course'],
            },
        ),
    ]
