# Generated by Django 5.1.5 on 2025-01-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID session')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Hyperlink to payment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Payment',
                'verbose_name_plural': 'Course Payments',
                'ordering': ['-course'],
            },
        ),
    ]
